/*Bryan Patten
patten_a06c.js
INFO 2124
Lisa Thoendel
01/23/2020*/
//winning numbers: 22, 42, 43, 47, 61;

let lottoPicks = [];
let powerBallPick = getLottoNumber(); 
let winnings = 0; 

/* WRITE YOUR SOLUTION BETWEEN THIS LINE */
while (lottoPicks.length < 5) {
        let p = getLottoNumber();
        lottoPicks.push(p);
}
/*While the length of the lottoPicks array is less than 5, a random number will be generated by the getLottoNumber
function, that number will be stored in the variable p, then added to the lottoPicks array*/
for (let i = 0; i < lottoPicks.length; i++) {
    switch(getLottoNumber()) {
        case 22: winnings = winnings + 10;
        break;
        case 42: winnings = winnings + 10;
        break;
        case 43: winnings = winnings + 10;
        break;
        case 47: winnings = winnings + 10;
        break;
        case 61: winnings = winnings + 10;
        break;  
        case powerBallPick: winnings = winnings + 100;              
    }
}
/*For as long as the variable i is less than the length of the lottoPicks array, it will check to see if the number
generated by the function getLottoNumber matches any of the winning number cases. If a number is matched, it adds a set 
amount to the winnings variable*/
if (winnings != 0) {
    console.log("Congratulations! You won $", winnings, "!");
} else {
    console.log("Sorry, you didn't win anything. Better luck next time!");
}  
/*If the winnings variable does not equal 0 when the while loop ends, the player is congratulated and told their amount
of winnings. If the winnings variable equals 0 then the player is told they win nothing*/

/* AND THIS LINE */

function getLottoNumber() {
    //returns a random number between 1 and 100;
    const min = Math.ceil(1);       //Minimum value;
    const max = Math.floor(100);    //Maximum value;
    return Math.floor(Math.random() * (max - min)) + min;
}